# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gensim', '0003_word_amount_of_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=255),
        ),
    ]
