# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gensim', '0004_auto_20160720_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='sequence',
            field=models.IntegerField(null=True),
        ),
    ]
