# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'cat1',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('authorid', models.CharField(blank=True, db_column='AuthorID', max_length=255, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('score', models.IntegerField(blank=True, db_column='Score', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('authorshortname', models.CharField(blank=True, db_column='AuthorShortname', max_length=50, null=True)),
                ('sentiment', models.FloatField(blank=True, db_column='Sentiment', null=True)),
                ('meanarousal', models.FloatField(blank=True, db_column='meanArousal', null=True)),
                ('stdvarousal', models.FloatField(blank=True, db_column='stdvArousal', null=True)),
                ('meanvalence', models.FloatField(blank=True, db_column='meanValence', null=True)),
                ('stdvvalence', models.FloatField(blank=True, db_column='stdvValence', null=True)),
                ('changed', models.IntegerField(blank=True, null=True)),
                ('vmeansum', models.FloatField(blank=True, db_column='vMeanSum', null=True)),
                ('ameansum', models.FloatField(blank=True, db_column='aMeanSum', null=True)),
                ('dmeansum', models.FloatField(blank=True, db_column='dMeanSum', null=True)),
                ('vmeansum2', models.FloatField(blank=True, db_column='vMeanSum2', null=True)),
                ('ameansum2', models.FloatField(blank=True, db_column='aMeanSum2', null=True)),
                ('dmeansum2', models.FloatField(blank=True, db_column='dMeanSum2', null=True)),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='ExtraSettings',
            fields=[
                ('setting_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('setting_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'extra_settings',
            },
        ),
        migrations.CreateModel(
            name='GeneralStats',
            fields=[
                ('stat_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('stat_value', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'general_stats',
            },
        ),
        migrations.CreateModel(
            name='HotTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.TextField(blank=True, null=True)),
                ('algorithm', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hot_topics',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('newsitemid', models.IntegerField(db_column='NewsItemId')),
                ('imagetype', models.CharField(db_column='ImageType', max_length=25)),
                ('image', models.TextField(db_column='Image')),
                ('imagesize', models.CharField(db_column='ImageSize', max_length=25)),
                ('imagecategory', models.CharField(blank=True, db_column='ImageCategory', max_length=25, null=True)),
                ('imagename', models.CharField(db_column='ImageName', max_length=255)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('newsitem', models.IntegerField()),
                ('tag', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'labels',
            },
        ),
        migrations.CreateModel(
            name='Newsitem',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('lead', models.TextField(blank=True, db_column='Lead', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('views', models.IntegerField(blank=True, db_column='Views', null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('url', models.CharField(blank=True, db_column='Url', max_length=200, null=True)),
                ('idauthor', models.TextField(blank=True, db_column='IdAuthor', null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('cat1', models.IntegerField(blank=True, null=True)),
                ('cat2', models.IntegerField(blank=True, null=True)),
                ('cat3', models.IntegerField(blank=True, null=True)),
                ('cat4', models.IntegerField(blank=True, null=True)),
                ('cat5', models.IntegerField(blank=True, null=True)),
                ('twitter', models.IntegerField(db_column='Twitter', default=0)),
                ('facebook', models.IntegerField(db_column='Facebook', default=0)),
                ('googleplus', models.IntegerField(db_column='GooglePlus', default=0)),
                ('pinit', models.IntegerField(db_column='PinIt', default=0)),
                ('vmeansum', models.FloatField(blank=True, db_column='vMeanSum', null=True)),
                ('ameansum', models.FloatField(blank=True, db_column='aMeanSum', null=True)),
                ('dmeansum', models.FloatField(blank=True, db_column='dMeanSum', null=True)),
                ('vmeansum2', models.FloatField(blank=True, db_column='vMeanSum2', null=True)),
                ('ameansum2', models.FloatField(blank=True, db_column='aMeanSum2', null=True)),
                ('dmeansum2', models.FloatField(blank=True, db_column='dMeanSum2', null=True)),
                ('vmeansum3', models.FloatField(blank=True, db_column='vMeanSum3', null=True)),
                ('ameansum3', models.FloatField(blank=True, db_column='aMeanSum3', null=True)),
                ('dmeansum3', models.FloatField(blank=True, db_column='dMeanSum3', null=True)),
            ],
            options={
                'db_table': 'NewsItem',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Permission',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('f1', models.SmallIntegerField(db_column='F1', primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, db_column='Word', max_length=21, null=True)),
                ('v_mean_sum', models.CharField(blank=True, db_column='V.Mean.Sum', max_length=4, null=True)),
                ('v_sd_sum', models.CharField(blank=True, db_column='V.SD.Sum', max_length=4, null=True)),
                ('v_rat_sum', models.SmallIntegerField(blank=True, db_column='V.Rat.Sum', null=True)),
                ('a_mean_sum', models.CharField(blank=True, db_column='A.Mean.Sum', max_length=4, null=True)),
                ('a_sd_sum', models.CharField(blank=True, db_column='A.SD.Sum', max_length=4, null=True)),
                ('a_rat_sum', models.SmallIntegerField(blank=True, db_column='A.Rat.Sum', null=True)),
                ('d_mean_sum', models.CharField(blank=True, db_column='D.Mean.Sum', max_length=4, null=True)),
                ('d_sd_sum', models.CharField(blank=True, db_column='D.SD.Sum', max_length=4, null=True)),
                ('d_rat_sum', models.SmallIntegerField(blank=True, db_column='D.Rat.Sum', null=True)),
                ('v_mean_m', models.CharField(blank=True, db_column='V.Mean.M', max_length=4, null=True)),
                ('v_sd_m', models.CharField(blank=True, db_column='V.SD.M', max_length=4, null=True)),
                ('v_rat_m', models.SmallIntegerField(blank=True, db_column='V.Rat.M', null=True)),
                ('v_mean_f', models.CharField(blank=True, db_column='V.Mean.F', max_length=4, null=True)),
                ('v_sd_f', models.CharField(blank=True, db_column='V.SD.F', max_length=4, null=True)),
                ('v_rat_f', models.SmallIntegerField(blank=True, db_column='V.Rat.F', null=True)),
                ('a_mean_m', models.CharField(blank=True, db_column='A.Mean.M', max_length=4, null=True)),
                ('a_sd_m', models.CharField(blank=True, db_column='A.SD.M', max_length=4, null=True)),
                ('a_rat_m', models.SmallIntegerField(blank=True, db_column='A.Rat.M', null=True)),
                ('a_mean_f', models.CharField(blank=True, db_column='A.Mean.F', max_length=4, null=True)),
                ('a_sd_f', models.CharField(blank=True, db_column='A.SD.F', max_length=4, null=True)),
                ('a_rat_f', models.SmallIntegerField(blank=True, db_column='A.Rat.F', null=True)),
                ('d_mean_m', models.CharField(blank=True, db_column='D.Mean.M', max_length=4, null=True)),
                ('d_sd_m', models.CharField(blank=True, db_column='D.SD.M', max_length=4, null=True)),
                ('d_rat_m', models.SmallIntegerField(blank=True, db_column='D.Rat.M', null=True)),
                ('d_mean_f', models.CharField(blank=True, db_column='D.Mean.F', max_length=4, null=True)),
                ('d_sd_f', models.CharField(blank=True, db_column='D.SD.F', max_length=4, null=True)),
                ('d_rat_f', models.SmallIntegerField(blank=True, db_column='D.Rat.F', null=True)),
                ('v_mean_y', models.CharField(blank=True, db_column='V.Mean.Y', max_length=4, null=True)),
                ('v_sd_y', models.CharField(blank=True, db_column='V.SD.Y', max_length=4, null=True)),
                ('v_rat_y', models.SmallIntegerField(blank=True, db_column='V.Rat.Y', null=True)),
                ('v_mean_o', models.CharField(blank=True, db_column='V.Mean.O', max_length=4, null=True)),
                ('v_sd_o', models.CharField(blank=True, db_column='V.SD.O', max_length=4, null=True)),
                ('v_rat_o', models.SmallIntegerField(blank=True, db_column='V.Rat.O', null=True)),
                ('a_mean_y', models.CharField(blank=True, db_column='A.Mean.Y', max_length=4, null=True)),
                ('a_sd_y', models.CharField(blank=True, db_column='A.SD.Y', max_length=4, null=True)),
                ('a_rat_y', models.SmallIntegerField(blank=True, db_column='A.Rat.Y', null=True)),
                ('a_mean_o', models.CharField(blank=True, db_column='A.Mean.O', max_length=4, null=True)),
                ('a_sd_o', models.CharField(blank=True, db_column='A.SD.O', max_length=4, null=True)),
                ('a_rat_o', models.SmallIntegerField(blank=True, db_column='A.Rat.O', null=True)),
                ('d_mean_y', models.CharField(blank=True, db_column='D.Mean.Y', max_length=4, null=True)),
                ('d_sd_y', models.CharField(blank=True, db_column='D.SD.Y', max_length=4, null=True)),
                ('d_rat_y', models.SmallIntegerField(blank=True, db_column='D.Rat.Y', null=True)),
                ('d_mean_o', models.CharField(blank=True, db_column='D.Mean.O', max_length=4, null=True)),
                ('d_sd_o', models.CharField(blank=True, db_column='D.SD.O', max_length=4, null=True)),
                ('d_rat_o', models.SmallIntegerField(blank=True, db_column='D.Rat.O', null=True)),
                ('v_mean_l', models.CharField(blank=True, db_column='V.Mean.L', max_length=4, null=True)),
                ('v_sd_l', models.CharField(blank=True, db_column='V.SD.L', max_length=4, null=True)),
                ('v_rat_l', models.SmallIntegerField(blank=True, db_column='V.Rat.L', null=True)),
                ('v_mean_h', models.CharField(blank=True, db_column='V.Mean.H', max_length=4, null=True)),
                ('v_sd_h', models.CharField(blank=True, db_column='V.SD.H', max_length=4, null=True)),
                ('v_rat_h', models.SmallIntegerField(blank=True, db_column='V.Rat.H', null=True)),
                ('a_mean_l', models.CharField(blank=True, db_column='A.Mean.L', max_length=4, null=True)),
                ('a_sd_l', models.CharField(blank=True, db_column='A.SD.L', max_length=4, null=True)),
                ('a_rat_l', models.SmallIntegerField(blank=True, db_column='A.Rat.L', null=True)),
                ('a_mean_h', models.CharField(blank=True, db_column='A.Mean.H', max_length=4, null=True)),
                ('a_sd_h', models.CharField(blank=True, db_column='A.SD.H', max_length=4, null=True)),
                ('a_rat_h', models.SmallIntegerField(blank=True, db_column='A.Rat.H', null=True)),
                ('d_mean_l', models.CharField(blank=True, db_column='D.Mean.L', max_length=4, null=True)),
                ('d_sd_l', models.CharField(blank=True, db_column='D.SD.L', max_length=4, null=True)),
                ('d_rat_l', models.SmallIntegerField(blank=True, db_column='D.Rat.L', null=True)),
                ('d_mean_h', models.CharField(blank=True, db_column='D.Mean.H', max_length=4, null=True)),
                ('d_sd_h', models.CharField(blank=True, db_column='D.SD.H', max_length=4, null=True)),
                ('d_rat_h', models.SmallIntegerField(blank=True, db_column='D.Rat.H', null=True)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('createdbyid', models.IntegerField(db_column='createdById')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
                ('updatedbyid', models.IntegerField(blank=True, db_column='updatedById', null=True)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Rolepermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(db_column='roleName', max_length=35)),
                ('permissionname', models.CharField(db_column='permissionName', max_length=35)),
            ],
            options={
                'db_table': 'RolePermission',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_column='firstName', max_length=35)),
                ('lastname', models.CharField(db_column='lastName', max_length=35)),
                ('email', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=64)),
                ('oldpassword', models.CharField(db_column='oldPassword', max_length=64)),
                ('role', models.CharField(max_length=25)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('createdbyid', models.IntegerField(db_column='createdById')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('updatedbyid', models.IntegerField(db_column='updatedById')),
                ('timezone', models.CharField(blank=True, db_column='timeZone', max_length=35, null=True)),
                ('status', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=10)),
                ('noun', models.CharField(blank=True, max_length=100)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss_parser.Comment')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=set([('rolename', 'permissionname')]),
        ),
        migrations.AddField(
            model_name='comment',
            name='newsitem',
            field=models.ForeignKey(blank=True, db_column='NewsItemID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rss_parser.Newsitem'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rss_parser.Comment'),
        ),
    ]
