# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 14:17
from __future__ import unicode_literals

import readchar

from django.db import migrations

def initial_data(apps, schema_editor):
    files_to_import = ['Permission.sql',
                       'Role.sql',
                       'RolePermission.sql',
                       'User.sql']
    for filename in files_to_import:                       
        with open("rss_parser/sql/"+filename) as input_file:
            for line in input_file:
                stripped_line = line.strip()
                if stripped_line != "" and not stripped_line.startswith('--'):
                    schema_editor.execute(line.strip())
                    
def delete_initial_data(apps, schema_editor):
    entities = ['Permission','Role','RolePermission','User']
    print("This will delete *ALL* the data from the following entities: ")
    print("\n".join(entities))
    print("Are you sure? (Y/N)")
    readed_char = readchar.readchar()
    if readed_char in ["Y","y"]:
        for entity in entities:
            migrations.RunSQL("DELETE FROM {0};".format(entity))

class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_data, delete_initial_data),
    ]
