# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0005_auto_20160718_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='noun',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='tag',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=200),
        ),
    ]
