# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0006_auto_20160718_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rss_parser.Text'),
        ),
    ]
