# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0008_auto_20160718_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='newsitem',
            name='topics',
            field=models.ManyToManyField(to='rss_parser.Topic'),
        ),
    ]
