# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0009_auto_20160719_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rss_parser.Comment'),
        ),
    ]
