# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0015_auto_20160725_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
