# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0016_text_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='aSDSum2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='dSDSum2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='vSDSum2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='aSDSum2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='dSDSum2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='vSDSum2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
