# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 12:43
from __future__ import unicode_literals

from nltk.tokenize import RegexpTokenizer

from django.db import migrations, models

from comment_parser.queryset_iterator import queryset_iterator

from rss_parser.models import Text

class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0017_auto_20160726_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='wordcount',
            field=models.IntegerField(default=0),
        ),        
    ]
