# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0019_move_content_to_text_calc_wordcount'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='newsitem',
            table='newsitem',
        ),
        migrations.AlterModelTable(
            name='text',
            table='text',
        ),
        migrations.AlterModelTable(
            name='word',
            table='word',
        ),
    ]
