# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0020_auto_20160913_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='newsitem',
            name='categories',
            field=models.ManyToManyField(blank=True, to='rss_parser.Category'),
        ),
    ]
