# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0022_auto_20160914_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lower_label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
