# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0023_category_lower_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='lower_label',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, db_column='Date', db_index=True, null=True),
        ),
    ]
