# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-21 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0025_auto_20161109_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('min_threshold', models.FloatField()),
                ('max_threshold', models.FloatField()),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss_parser.Algorithm')),
            ],
            options={
                'db_table': 'algorithm_color',
            },
        ),
        migrations.AlterUniqueTogether(
            name='algorithmcolor',
            unique_together=set([('algorithm', 'color')]),
        ),
    ]
