# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-24 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0026_auto_20161121_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=2000)),
                ('score', models.FloatField()),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss_parser.Algorithm')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss_parser.Text')),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
    ]
