# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-01 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0027_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('long_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='AuthorSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_nr_words', models.FloatField()),
                ('avg_wordlen', models.FloatField()),
                ('avg_words_gt6', models.FloatField()),
                ('avg_personal', models.FloatField()),
                ('avg_collective', models.FloatField()),
                ('indegree', models.FloatField()),
                ('indegree_centrality', models.FloatField()),
                ('outdegree', models.FloatField()),
                ('outdegree_centrality', models.FloatField()),
                ('degree', models.FloatField()),
                ('degree_centrality', models.FloatField()),
                ('avg_shared', models.FloatField()),
                ('pagerank', models.FloatField()),
                ('pagerank_weighted', models.FloatField()),
                ('nr_posts', models.IntegerField()),
                ('hub_score', models.FloatField()),
                ('authority_score', models.FloatField()),
                ('betweeness_centrality', models.FloatField()),
                ('closeness_centrality', models.FloatField()),
                ('clustering_coef', models.FloatField()),
                ('eccentricity', models.FloatField()),
                ('constraint', models.FloatField()),
                ('polarity_arousal', models.FloatField()),
                ('polarity_valence', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss_parser.Author')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rss_parser.Author'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rss_parser.Author'),
        ),
    ]
