# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-01 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0028_auto_20161201_1049'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authorsummary',
            table='author_summary',
        ),
    ]
