# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-01 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0029_auto_20161201_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='long_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
